/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LicencaRouteImport } from './routes/licenca'
import { Route as GeradorCatalogoRouteImport } from './routes/gerador-catalogo'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as EsqueciASenhaRouteImport } from './routes/esqueci-a-senha'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as CobrancaRouteImport } from './routes/cobranca'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BuscaVisualRouteImport } from './routes/busca-visual'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoIndexRouteImport } from './routes/catalogo.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as PagamentoSucessoRouteImport } from './routes/pagamento.sucesso'
import { Route as CatalogoSlugRouteImport } from './routes/catalogo.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ArtesSlugRouteImport } from './routes/artes.$slug'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated/minha-conta'
import { Route as AuthenticatedCarrinhoRouteImport } from './routes/_authenticated/carrinho'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as PagamentoPixOrderIdRouteImport } from './routes/pagamento.pix.$orderId'
import { Route as AuthenticatedAdminVendasRouteImport } from './routes/_authenticated/admin/vendas'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminTagsRouteImport } from './routes/_authenticated/admin/tags'
import { Route as AuthenticatedAdminSuporteRouteImport } from './routes/_authenticated/admin/suporte'
import { Route as AuthenticatedAdminSeoCheckRouteImport } from './routes/_authenticated/admin/seo-check'
import { Route as AuthenticatedAdminPlanosRouteImport } from './routes/_authenticated/admin/planos'
import { Route as AuthenticatedAdminImportarRouteImport } from './routes/_authenticated/admin/importar'
import { Route as AuthenticatedAdminHomeRouteImport } from './routes/_authenticated/admin/home'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated/admin/emails'
import { Route as AuthenticatedAdminCuponsRouteImport } from './routes/_authenticated/admin/cupons'
import { Route as AuthenticatedAdminConteudosRouteImport } from './routes/_authenticated/admin/conteudos'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin/categorias'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin/blog'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin/banners'
import { Route as AuthenticatedAdminAvaliacoesRouteImport } from './routes/_authenticated/admin/avaliacoes'
import { Route as AuthenticatedAdminArtesRouteImport } from './routes/_authenticated/admin/artes'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as ApiPublicOrdersCleanupExpiredRouteImport } from './routes/api/public/orders/cleanup-expired'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago/webhook'
import { Route as AuthenticatedAdminPedidosIdRouteImport } from './routes/_authenticated/admin/pedidos.$id'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LicencaRoute = LicencaRouteImport.update({
  id: '/licenca',
  path: '/licenca',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorCatalogoRoute = GeradorCatalogoRouteImport.update({
  id: '/gerador-catalogo',
  path: '/gerador-catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciASenhaRoute = EsqueciASenhaRouteImport.update({
  id: '/esqueci-a-senha',
  path: '/esqueci-a-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrancaRoute = CobrancaRouteImport.update({
  id: '/cobranca',
  path: '/cobranca',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaVisualRoute = BuscaVisualRouteImport.update({
  id: '/busca-visual',
  path: '/busca-visual',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoIndexRoute = CatalogoIndexRouteImport.update({
  id: '/catalogo/',
  path: '/catalogo/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoSucessoRoute = PagamentoSucessoRouteImport.update({
  id: '/pagamento/sucesso',
  path: '/pagamento/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoSlugRoute = CatalogoSlugRouteImport.update({
  id: '/catalogo/$slug',
  path: '/catalogo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtesSlugRoute = ArtesSlugRouteImport.update({
  id: '/artes/$slug',
  path: '/artes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarrinhoRoute = AuthenticatedCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const PagamentoPixOrderIdRoute = PagamentoPixOrderIdRouteImport.update({
  id: '/pagamento/pix/$orderId',
  path: '/pagamento/pix/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminVendasRoute =
  AuthenticatedAdminVendasRouteImport.update({
    id: '/vendas',
    path: '/vendas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTagsRoute = AuthenticatedAdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSuporteRoute =
  AuthenticatedAdminSuporteRouteImport.update({
    id: '/suporte',
    path: '/suporte',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSeoCheckRoute =
  AuthenticatedAdminSeoCheckRouteImport.update({
    id: '/seo-check',
    path: '/seo-check',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlanosRoute =
  AuthenticatedAdminPlanosRouteImport.update({
    id: '/planos',
    path: '/planos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminImportarRoute =
  AuthenticatedAdminImportarRouteImport.update({
    id: '/importar',
    path: '/importar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHomeRoute = AuthenticatedAdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCuponsRoute =
  AuthenticatedAdminCuponsRouteImport.update({
    id: '/cupons',
    path: '/cupons',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConteudosRoute =
  AuthenticatedAdminConteudosRouteImport.update({
    id: '/conteudos',
    path: '/conteudos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAvaliacoesRoute =
  AuthenticatedAdminAvaliacoesRouteImport.update({
    id: '/avaliacoes',
    path: '/avaliacoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminArtesRoute = AuthenticatedAdminArtesRouteImport.update({
  id: '/artes',
  path: '/artes',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrdersCleanupExpiredRoute =
  ApiPublicOrdersCleanupExpiredRouteImport.update({
    id: '/api/public/orders/cleanup-expired',
    path: '/api/public/orders/cleanup-expired',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago/webhook',
    path: '/api/public/mercadopago/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminPedidosIdRoute =
  AuthenticatedAdminPedidosIdRouteImport.update({
    id: '/pedidos/$id',
    path: '/pedidos/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca-visual': typeof BuscaVisualRoute
  '/cadastro': typeof CadastroRoute
  '/cobranca': typeof CobrancaRoute
  '/downloads': typeof DownloadsRoute
  '/esqueci-a-senha': typeof EsqueciASenhaRoute
  '/favoritos': typeof FavoritosRoute
  '/gerador-catalogo': typeof GeradorCatalogoRoute
  '/licenca': typeof LicencaRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/carrinho': typeof AuthenticatedCarrinhoRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/artes/$slug': typeof ArtesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/blog/': typeof BlogIndexRoute
  '/catalogo/': typeof CatalogoIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/artes': typeof AuthenticatedAdminArtesRoute
  '/admin/avaliacoes': typeof AuthenticatedAdminAvaliacoesRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/conteudos': typeof AuthenticatedAdminConteudosRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/home': typeof AuthenticatedAdminHomeRoute
  '/admin/importar': typeof AuthenticatedAdminImportarRoute
  '/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/admin/seo-check': typeof AuthenticatedAdminSeoCheckRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/vendas': typeof AuthenticatedAdminVendasRoute
  '/pagamento/pix/$orderId': typeof PagamentoPixOrderIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/orders/cleanup-expired': typeof ApiPublicOrdersCleanupExpiredRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca-visual': typeof BuscaVisualRoute
  '/cadastro': typeof CadastroRoute
  '/cobranca': typeof CobrancaRoute
  '/downloads': typeof DownloadsRoute
  '/esqueci-a-senha': typeof EsqueciASenhaRoute
  '/favoritos': typeof FavoritosRoute
  '/gerador-catalogo': typeof GeradorCatalogoRoute
  '/licenca': typeof LicencaRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/carrinho': typeof AuthenticatedCarrinhoRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/artes/$slug': typeof ArtesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/blog': typeof BlogIndexRoute
  '/catalogo': typeof CatalogoIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/artes': typeof AuthenticatedAdminArtesRoute
  '/admin/avaliacoes': typeof AuthenticatedAdminAvaliacoesRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/conteudos': typeof AuthenticatedAdminConteudosRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/home': typeof AuthenticatedAdminHomeRoute
  '/admin/importar': typeof AuthenticatedAdminImportarRoute
  '/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/admin/seo-check': typeof AuthenticatedAdminSeoCheckRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/vendas': typeof AuthenticatedAdminVendasRoute
  '/pagamento/pix/$orderId': typeof PagamentoPixOrderIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/orders/cleanup-expired': typeof ApiPublicOrdersCleanupExpiredRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/busca-visual': typeof BuscaVisualRoute
  '/cadastro': typeof CadastroRoute
  '/cobranca': typeof CobrancaRoute
  '/downloads': typeof DownloadsRoute
  '/esqueci-a-senha': typeof EsqueciASenhaRoute
  '/favoritos': typeof FavoritosRoute
  '/gerador-catalogo': typeof GeradorCatalogoRoute
  '/licenca': typeof LicencaRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/carrinho': typeof AuthenticatedCarrinhoRoute
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/artes/$slug': typeof ArtesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/blog/': typeof BlogIndexRoute
  '/catalogo/': typeof CatalogoIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/artes': typeof AuthenticatedAdminArtesRoute
  '/_authenticated/admin/avaliacoes': typeof AuthenticatedAdminAvaliacoesRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/conteudos': typeof AuthenticatedAdminConteudosRoute
  '/_authenticated/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/home': typeof AuthenticatedAdminHomeRoute
  '/_authenticated/admin/importar': typeof AuthenticatedAdminImportarRoute
  '/_authenticated/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/_authenticated/admin/seo-check': typeof AuthenticatedAdminSeoCheckRoute
  '/_authenticated/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/_authenticated/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/vendas': typeof AuthenticatedAdminVendasRoute
  '/pagamento/pix/$orderId': typeof PagamentoPixOrderIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/orders/cleanup-expired': typeof ApiPublicOrdersCleanupExpiredRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca-visual'
    | '/cadastro'
    | '/cobranca'
    | '/downloads'
    | '/esqueci-a-senha'
    | '/favoritos'
    | '/gerador-catalogo'
    | '/licenca'
    | '/login'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/suporte'
    | '/termos'
    | '/admin'
    | '/carrinho'
    | '/minha-conta'
    | '/artes/$slug'
    | '/blog/$slug'
    | '/catalogo/$slug'
    | '/pagamento/sucesso'
    | '/blog/'
    | '/catalogo/'
    | '/admin/analytics'
    | '/admin/artes'
    | '/admin/avaliacoes'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/conteudos'
    | '/admin/cupons'
    | '/admin/emails'
    | '/admin/home'
    | '/admin/importar'
    | '/admin/planos'
    | '/admin/seo-check'
    | '/admin/suporte'
    | '/admin/tags'
    | '/admin/usuarios'
    | '/admin/vendas'
    | '/pagamento/pix/$orderId'
    | '/admin/'
    | '/admin/pedidos/$id'
    | '/api/public/mercadopago/webhook'
    | '/api/public/orders/cleanup-expired'
    | '/api/public/stripe/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca-visual'
    | '/cadastro'
    | '/cobranca'
    | '/downloads'
    | '/esqueci-a-senha'
    | '/favoritos'
    | '/gerador-catalogo'
    | '/licenca'
    | '/login'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/suporte'
    | '/termos'
    | '/carrinho'
    | '/minha-conta'
    | '/artes/$slug'
    | '/blog/$slug'
    | '/catalogo/$slug'
    | '/pagamento/sucesso'
    | '/blog'
    | '/catalogo'
    | '/admin/analytics'
    | '/admin/artes'
    | '/admin/avaliacoes'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/conteudos'
    | '/admin/cupons'
    | '/admin/emails'
    | '/admin/home'
    | '/admin/importar'
    | '/admin/planos'
    | '/admin/seo-check'
    | '/admin/suporte'
    | '/admin/tags'
    | '/admin/usuarios'
    | '/admin/vendas'
    | '/pagamento/pix/$orderId'
    | '/admin'
    | '/admin/pedidos/$id'
    | '/api/public/mercadopago/webhook'
    | '/api/public/orders/cleanup-expired'
    | '/api/public/stripe/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/busca-visual'
    | '/cadastro'
    | '/cobranca'
    | '/downloads'
    | '/esqueci-a-senha'
    | '/favoritos'
    | '/gerador-catalogo'
    | '/licenca'
    | '/login'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/suporte'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/carrinho'
    | '/_authenticated/minha-conta'
    | '/artes/$slug'
    | '/blog/$slug'
    | '/catalogo/$slug'
    | '/pagamento/sucesso'
    | '/blog/'
    | '/catalogo/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/artes'
    | '/_authenticated/admin/avaliacoes'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/conteudos'
    | '/_authenticated/admin/cupons'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/home'
    | '/_authenticated/admin/importar'
    | '/_authenticated/admin/planos'
    | '/_authenticated/admin/seo-check'
    | '/_authenticated/admin/suporte'
    | '/_authenticated/admin/tags'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/vendas'
    | '/pagamento/pix/$orderId'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/pedidos/$id'
    | '/api/public/mercadopago/webhook'
    | '/api/public/orders/cleanup-expired'
    | '/api/public/stripe/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BuscaVisualRoute: typeof BuscaVisualRoute
  CadastroRoute: typeof CadastroRoute
  CobrancaRoute: typeof CobrancaRoute
  DownloadsRoute: typeof DownloadsRoute
  EsqueciASenhaRoute: typeof EsqueciASenhaRoute
  FavoritosRoute: typeof FavoritosRoute
  GeradorCatalogoRoute: typeof GeradorCatalogoRoute
  LicencaRoute: typeof LicencaRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
  ArtesSlugRoute: typeof ArtesSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CatalogoSlugRoute: typeof CatalogoSlugRoute
  PagamentoSucessoRoute: typeof PagamentoSucessoRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CatalogoIndexRoute: typeof CatalogoIndexRoute
  PagamentoPixOrderIdRoute: typeof PagamentoPixOrderIdRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
  ApiPublicOrdersCleanupExpiredRoute: typeof ApiPublicOrdersCleanupExpiredRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenca': {
      id: '/licenca'
      path: '/licenca'
      fullPath: '/licenca'
      preLoaderRoute: typeof LicencaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador-catalogo': {
      id: '/gerador-catalogo'
      path: '/gerador-catalogo'
      fullPath: '/gerador-catalogo'
      preLoaderRoute: typeof GeradorCatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-a-senha': {
      id: '/esqueci-a-senha'
      path: '/esqueci-a-senha'
      fullPath: '/esqueci-a-senha'
      preLoaderRoute: typeof EsqueciASenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobranca': {
      id: '/cobranca'
      path: '/cobranca'
      fullPath: '/cobranca'
      preLoaderRoute: typeof CobrancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca-visual': {
      id: '/busca-visual'
      path: '/busca-visual'
      fullPath: '/busca-visual'
      preLoaderRoute: typeof BuscaVisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/': {
      id: '/catalogo/'
      path: '/catalogo'
      fullPath: '/catalogo/'
      preLoaderRoute: typeof CatalogoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/sucesso': {
      id: '/pagamento/sucesso'
      path: '/pagamento/sucesso'
      fullPath: '/pagamento/sucesso'
      preLoaderRoute: typeof PagamentoSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$slug': {
      id: '/catalogo/$slug'
      path: '/catalogo/$slug'
      fullPath: '/catalogo/$slug'
      preLoaderRoute: typeof CatalogoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artes/$slug': {
      id: '/artes/$slug'
      path: '/artes/$slug'
      fullPath: '/artes/$slug'
      preLoaderRoute: typeof ArtesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carrinho': {
      id: '/_authenticated/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof AuthenticatedCarrinhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/pagamento/pix/$orderId': {
      id: '/pagamento/pix/$orderId'
      path: '/pagamento/pix/$orderId'
      fullPath: '/pagamento/pix/$orderId'
      preLoaderRoute: typeof PagamentoPixOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/vendas': {
      id: '/_authenticated/admin/vendas'
      path: '/vendas'
      fullPath: '/admin/vendas'
      preLoaderRoute: typeof AuthenticatedAdminVendasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tags': {
      id: '/_authenticated/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AuthenticatedAdminTagsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/suporte': {
      id: '/_authenticated/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AuthenticatedAdminSuporteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/seo-check': {
      id: '/_authenticated/admin/seo-check'
      path: '/seo-check'
      fullPath: '/admin/seo-check'
      preLoaderRoute: typeof AuthenticatedAdminSeoCheckRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/planos': {
      id: '/_authenticated/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AuthenticatedAdminPlanosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/importar': {
      id: '/_authenticated/admin/importar'
      path: '/importar'
      fullPath: '/admin/importar'
      preLoaderRoute: typeof AuthenticatedAdminImportarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/home': {
      id: '/_authenticated/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AuthenticatedAdminHomeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cupons': {
      id: '/_authenticated/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AuthenticatedAdminCuponsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/conteudos': {
      id: '/_authenticated/admin/conteudos'
      path: '/conteudos'
      fullPath: '/admin/conteudos'
      preLoaderRoute: typeof AuthenticatedAdminConteudosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/avaliacoes': {
      id: '/_authenticated/admin/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AuthenticatedAdminAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/artes': {
      id: '/_authenticated/admin/artes'
      path: '/artes'
      fullPath: '/admin/artes'
      preLoaderRoute: typeof AuthenticatedAdminArtesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/orders/cleanup-expired': {
      id: '/api/public/orders/cleanup-expired'
      path: '/api/public/orders/cleanup-expired'
      fullPath: '/api/public/orders/cleanup-expired'
      preLoaderRoute: typeof ApiPublicOrdersCleanupExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago/webhook': {
      id: '/api/public/mercadopago/webhook'
      path: '/api/public/mercadopago/webhook'
      fullPath: '/api/public/mercadopago/webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/pedidos/$id': {
      id: '/_authenticated/admin/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedAdminPedidosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminArtesRoute: typeof AuthenticatedAdminArtesRoute
  AuthenticatedAdminAvaliacoesRoute: typeof AuthenticatedAdminAvaliacoesRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminConteudosRoute: typeof AuthenticatedAdminConteudosRoute
  AuthenticatedAdminCuponsRoute: typeof AuthenticatedAdminCuponsRoute
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminHomeRoute: typeof AuthenticatedAdminHomeRoute
  AuthenticatedAdminImportarRoute: typeof AuthenticatedAdminImportarRoute
  AuthenticatedAdminPlanosRoute: typeof AuthenticatedAdminPlanosRoute
  AuthenticatedAdminSeoCheckRoute: typeof AuthenticatedAdminSeoCheckRoute
  AuthenticatedAdminSuporteRoute: typeof AuthenticatedAdminSuporteRoute
  AuthenticatedAdminTagsRoute: typeof AuthenticatedAdminTagsRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminVendasRoute: typeof AuthenticatedAdminVendasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPedidosIdRoute: typeof AuthenticatedAdminPedidosIdRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminArtesRoute: AuthenticatedAdminArtesRoute,
    AuthenticatedAdminAvaliacoesRoute: AuthenticatedAdminAvaliacoesRoute,
    AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
    AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
    AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
    AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
    AuthenticatedAdminConteudosRoute: AuthenticatedAdminConteudosRoute,
    AuthenticatedAdminCuponsRoute: AuthenticatedAdminCuponsRoute,
    AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
    AuthenticatedAdminHomeRoute: AuthenticatedAdminHomeRoute,
    AuthenticatedAdminImportarRoute: AuthenticatedAdminImportarRoute,
    AuthenticatedAdminPlanosRoute: AuthenticatedAdminPlanosRoute,
    AuthenticatedAdminSeoCheckRoute: AuthenticatedAdminSeoCheckRoute,
    AuthenticatedAdminSuporteRoute: AuthenticatedAdminSuporteRoute,
    AuthenticatedAdminTagsRoute: AuthenticatedAdminTagsRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminVendasRoute: AuthenticatedAdminVendasRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminPedidosIdRoute: AuthenticatedAdminPedidosIdRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCarrinhoRoute: typeof AuthenticatedCarrinhoRoute
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCarrinhoRoute: AuthenticatedCarrinhoRoute,
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BuscaVisualRoute: BuscaVisualRoute,
  CadastroRoute: CadastroRoute,
  CobrancaRoute: CobrancaRoute,
  DownloadsRoute: DownloadsRoute,
  EsqueciASenhaRoute: EsqueciASenhaRoute,
  FavoritosRoute: FavoritosRoute,
  GeradorCatalogoRoute: GeradorCatalogoRoute,
  LicencaRoute: LicencaRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
  ArtesSlugRoute: ArtesSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  CatalogoSlugRoute: CatalogoSlugRoute,
  PagamentoSucessoRoute: PagamentoSucessoRoute,
  BlogIndexRoute: BlogIndexRoute,
  CatalogoIndexRoute: CatalogoIndexRoute,
  PagamentoPixOrderIdRoute: PagamentoPixOrderIdRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
  ApiPublicOrdersCleanupExpiredRoute: ApiPublicOrdersCleanupExpiredRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
