GRANT SELECT (
  id,
  slug,
  title,
  description,
  category_id,
  preview_url,
  file_path,
  file_format,
  colors,
  price_cents,
  is_published,
  is_featured,
  is_trending,
  download_count,
  view_count,
  created_at,
  updated_at,
  credit_cost,
  gallery_urls,
  translations,
  featured_order,
  seo_title,
  seo_description,
  seo_keyword,
  product_code,
  alt_text,
  noindex,
  tech_specs,
  resolution,
  dimensions,
  usage_instructions,
  license_text,
  license_type
) ON public.artworks TO anon;

GRANT SELECT (
  id,
  slug,
  title,
  description,
  category_id,
  preview_url,
  file_path,
  file_format,
  colors,
  price_cents,
  is_published,
  is_featured,
  is_trending,
  download_count,
  view_count,
  created_at,
  updated_at,
  credit_cost,
  gallery_urls,
  translations,
  featured_order,
  seo_title,
  seo_description,
  seo_keyword,
  product_code,
  alt_text,
  noindex,
  tech_specs,
  resolution,
  dimensions,
  usage_instructions,
  license_text,
  license_type
) ON public.artworks TO authenticated;

GRANT INSERT, UPDATE, DELETE ON public.artworks TO authenticated;
GRANT ALL ON public.artworks TO service_role;