TRUNCATE TABLE public.artworks CASCADE;
TRUNCATE TABLE public.categories CASCADE;
TRUNCATE TABLE public.tags CASCADE;
TRUNCATE TABLE public.artwork_categories CASCADE;
TRUNCATE TABLE public.artwork_tags CASCADE;
TRUNCATE TABLE public.reviews CASCADE;
TRUNCATE TABLE public.downloads CASCADE;
TRUNCATE TABLE public.cart_items CASCADE;
TRUNCATE TABLE public.favorites CASCADE;